[package]
name = "alkahest"
version = "0.2.0"
edition = "2021"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/alkahest"
homepage = "https://github.com/zakarumych/alkahest"
repository = "https://github.com/zakarumych/alkahest"
readme = "README.md"
description = "Fantastic serialization library with zero-overhead serialization and zero-copy deserialization"

[features]
alloc = [] # enables impls for types from `alloc` crate.
derive = ["alkahest-proc"]

# TODO: Control on value or type level?
# Keep features for defaults?
fixed8 = [] # sets size of `FixedUsize` and `FixedIsize` to 8 bits.
fixed16 = [] # sets size of `FixedUsize` and `FixedIsize` to 16 bits.
fixed32 = [] # sets size of `FixedUsize` and `FixedIsize` to 32 bits. Default.
fixed64 = [] # sets size of `FixedUsize` and `FixedIsize` to 64 bits.
default = ["alloc", "fixed32"]

[dependencies]
alkahest-proc = { version = "=0.2.0", path = "proc", optional = true }

[dev-dependencies]
criterion = { version = "0.4", features = ["real_blackbox"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
rkyv = { version = "0.7", features = ["validation"] }
bytecheck = "0.6"

[[example]]
name = "test"
required-features = ["derive"]

[[bench]]
name = "benchmark"
harness = false
required-features = ["derive"]

[workspace]
members = ["proc"]
